=== notrustverify/find-us/images.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/notrustverify/find-us/images.schema.json",
  "title": "Images",
  "description": "List of images of NTV stickers and their GPS coordinates",
  "type": "array",
  "items": {
    "type": "object",
    "title": "An image object",
    "minItems": 1,
    "properties": {
      "id": {
        "type": "integer",
        "title": "The id of the picture",
        "minimum": 0
      },
      "lat": {
        "type": "number",
        "title": "The latitude where the picture was taken"
      },
      "long": {
        "type": "number",
        "title": "The longitude where the picture was taken"
      },
      "name": {
        "type": "string",
        "title": "The name of the image in the 'images' folder"
      }
    },
    "required": [
        "id",
        "lat",
        "long",
        "name"
    ]
  }
}

=== notrustverify/find-us/images.json
[
  {
    "id": 0,
    "lat": 41.37832,
    "long": 2.18129,
    "name": "0.jpg"
  },
  {
    "id": 1,
    "lat": 56.41449,
    "long": -5.47424,
    "name": "1.jpg"
  },
  {
    "id": 2,
    "lat": 57.89768,
    "long": -6.80395,
    "name": "2.jpg"
  },
  {
    "id": 3,
    "lat": 46.97559,
    "long": 6.78862,
    "name": "3.jpg"
  },
  {
    "id": 4,
    "lat": 28.10967,
    "long": -14.49085,
    "name": "4.jpg"
  },
  {
    "id": 5,
    "lat": 28.10967,
    "long": -14.49085,
    "name": "5.jpg"
  },
  {
    "id": 6,
    "lat": 46.53123,
    "long": 7.66340,
    "name": "6.jpg"
  },
  {
    "id": 7,
    "lat": 46.75788,
    "long": 7.63076,
    "name": "7.jpg"
  },
  {
    "id": 8,
    "lat": 52.36433,
    "long": 4.88951,
    "name": "8.jpg"
  },
  {
    "id": 9,
    "lat": 52.37696,
    "long": 4.89840,
    "name": "9.jpg"
  }
]
